### PR TITLE
change to rename method

### PR DESCRIPTION
**Pull request by isratrade**

### CODE REVIEW

**Comment by isratrade** [comment]
@jmontleon, @jwmatthews, does anybody know what changed. I'm getting validation errors "MAC already taken, IP already taken, on the `rename` method, so I switched to `update_column` which is just a database update and doesn't check validation. Is this OK?

**Comment by jmontleon** [comment]
Do you have a host outside the org? I have had this happen to me a couple times. Not really sure what the reproducer is outside of something going wrong. Other possibility is left over DHCP records that didn't get cleaned up in /var/lib/dhcp/dhcpd.lease /var/named/dynamic/*

**Comment by isratrade** [comment]
Ok. Let's not merge this as best to have validations on the server-side.

**Comment by jwmatthews** [comment]
@isratrade should we keep this open and investigate further?

**Pull request closed without merging**
